<a href="https://colab.research.google.com/github/jangje0908/sesac/blob/main/Chapter2_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_%ED%8C%A8%ED%82%A4%EC%A7%80_scikit_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Chapter 2. 파이썬 빅데이터 분석 패키지**

## 3. 사이킷런(Scikit-learn)
- 머신러닝 분석을 수행할 때 가장 유용하게 사용할 수 있는 파이썬 라이브러리
- 머신러닝을 위한 가장 쉽고 효율적인 개발 라이브러리 제공

### (1) 사이킷런(Scikit-learn) 개요

####  사이킷런 임포트

In [ ]:
import sklearn
print(sklearn.__version__)   # scikit-learn 버전 확인

1.2.2


### (2) 사이킷런 기반 프레임워크 익히기
- 머신러닝 모델 학습을 위한 fit 함수와, 학습된 모델의 예측을 위한 predict 함수 제공
- 분류 알고리즘을 위한 클래스를 classifier로, 회귀 알고리즘을 위한 클래스를 regressor로 지칭

### (3) 사이킷런 주요 모듈

### (4) 사이킷런 내장 데이터세트

#### 붓꽃 데이터세트 불러오기

In [ ]:
from sklearn.datasets import load_iris

iris = load_iris()
print('붓꽃 데이터세트 타입 : ', type(iris))

keys = iris.keys()
print('붓꽃 데이터세트 키 : ', keys)

붓꽃 데이터세트 타입 :  <class 'sklearn.utils._bunch.Bunch'>
붓꽃 데이터세트 키 :  dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


#### 붓꽃 데이터세트 키 출력

In [ ]:
print('feature_names :')   # 독립변수의 변수명
print(iris.feature_names)
print('\ntarget_names :')   # 종속변수의 변수명
print(iris.target_names)
print('\ndata :')   # 독립변수의 데이터 값
print(iris.data)
print('\ntarget :')   # 종속변수의 데이터 값
print(iris.target)

feature_names :
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

target_names :
['setosa' 'versicolor' 'virginica']

data :
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1

### (5) 사이킷런 머신러닝 만들어 보기

#### 붓꽃 데이터세트 훑어보기

In [ ]:
import pandas as pd

iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label'] = iris.target
print(iris_df.head(3))

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0  


#### 학습/테스트 데이터세트 분할
- 학습 데이터와 테스트 데이터를 test_size 입력 매개변수 값의 비율로 쉽게 분할 가능
- test_size = 0.2 : 전체 데이터 중 테스트 데이터가 20%, 학습 데이터가 80%로 데이터 분할
- random_state : 함수를 호출할 떼마다 같은 학습/테스트 데이터 세트를 생성하기 위해 주어지는 난수 발생 값 -> train_test_split은 호출 시, 무작위로 데이터를 분리하므로 random_state를 지정하지 않으면 수행할 때마다 다른 학습/테스트 데이터 세트 생성

In [ ]:
from sklearn.model_selection import train_test_split

iris_data = iris.data
iris_label = iris.target

x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)
# x_train: 학습 피쳐 데이터 세트
# y_train: 학습 타겟 데이터 세트
# x_test: 테스트 피쳐 데이터 세트
# y_test: 테스트 타겟 데이터 세트

print('train dataset')
print('x_train dataset : ', len(x_train))
print('y_train dataset : ', len(y_train))
print('\ntest dataset')
print('x_test dataset : ', len(x_test))
print('y_test dataset : ', len(y_test))

train dataset
x_train dataset :  120
y_train dataset :  120

test dataset
x_test dataset :  30
y_test dataset :  30


#### 의사결정 트리 머신러닝 학습
- 머신러닝 분류 알고리즘의 하나인 의사결정 트리를 이용해 머신러닝 모델 학습과 예측
- 예측은 학습 데이터가 아닌 테스트 데이터 이용

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt_clf = DecisionTreeClassifier(random_state=11)
dt_clf.fit(x_train, y_train)

DecisionTreeClassifier(random_state=11)

#### 의사결정 트리 머신러닝 테스트/평가
- 정확도: 예측 결과가 실제 레이블 값과 얼마나 정확하게 맞는지를 평가하는 지표

In [ ]:
from sklearn.metrics import accuracy_score

pred = dt_clf.predict(x_test)
ac_score = accuracy_score(y_test, pred)   # accuraacy_score(타겟 데이터 세트, 예측 데이터 세트)

print('예측 정확도 : ', ac_score)

예측 정확도 :  0.9333333333333333


### (6) 사이킷런 데이터 전처리

#### 레이블 인코딩
- 명목형 변수를 코드형 숫자값으로 변환
- 냉장고가 1, 컴퓨터가 3으로 변환되면 1보다 3이 더 큰 값이므로 특정 머신러닝 알고리즘에서 가중치가 더 부여 -> 선형 회귀와 같은 알고리즘에는 적합하지 않음, 트리 계열의 머신러닝 알고리은 숫자의 이러한 특성을 반영하지 않으므로 레이블 인코딩을 활용해도 큰 영향이 없음

In [ ]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', 'TV', '냉장고', '컴퓨터', '컴퓨터']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

print('인코딩 변환값 : ', labels)
print('인코딩 클래스 : ', encoder.classes_)   # LabelEncoder().class_ 함수를 통해 속성값 확인

인코딩 변환값 :  [0 1 2 3 0 1 3 3]
인코딩 클래스 :  ['TV' '냉장고' '전자레인지' '컴퓨터']


#### 레이블 디코딩

In [ ]:
origins = encoder.inverse_transform([0, 1, 2, 3, 0, 1, 3, 3])   # 인코딩한 값을 다시 디코딩

print('디코딩 원본값 : ', origins)

디코딩 원본값 :  ['TV' '냉장고' '전자레인지' '컴퓨터' 'TV' '냉장고' '컴퓨터' '컴퓨터']


#### 원-핫 인코딩
- 위에서 말한 레이블 인코딩의 문제점 해결하기 위한 인코딩 방식
- 변수 값의 유형에 따라 새로운 변수를 추가해 고윳값에 해당하는 컬럼에만 1을 표시, 나머지 컬럼에는 0을 표시

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

labels = labels.reshape(-1, 1)   # 원핫인코딩은 입력 값으로 2차원 데이터가 필요

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]
원-핫 인코딩 데이터 차원
(8, 4)


#### 판다스의 원-핫 인코딩
- get_dummies: scikit-learn의 onehotencorder와 다르게 명목형 데이터를 숫자형으로 변환할 필요 없이 바로 2차원 데이터로 변환하여 인코딩 수행

In [ ]:
import pandas as pd

item_df = pd.DataFrame({'item':items})
print(pd.get_dummies(item_df))

   item_TV  item_냉장고  item_전자레인지  item_컴퓨터
0        1         0           0         0
1        0         1           0         0
2        0         0           1         0
3        0         0           0         1
4        1         0           0         0
5        0         1           0         0
6        0         0           0         1
7        0         0           0         1


#### 스케일링 데이터세트 훑어보기
- 스케일링: 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업
- 대표적인 방법으로 표준화와 정규화가 있음

In [ ]:
# 스케일링 적용하기에 앞서 원 데이터 세트의 평균값과 분산값 확인

from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature 들의 평균 값 :\n', iris_df.mean())
print('feature 들의 분산 값 :\n', iris_df.var())

feature 들의 평균 값 :
 sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
feature 들의 분산 값 :
 sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


#### 표준화
- 원 데이터를 평균이 0이고 분산이 1인 정규 분포를 가진 값으로 변환
- 원래 값에서 해당 데이터 세트의 평균을 뺀 값을 데이터 세트의 표준편차로 나누 값으로 계산

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('feature 들의 평균 값 :\n', iris_df_scaled.mean())
print('feature 들의 분산 값 :\n', iris_df_scaled.var())

feature 들의 평균 값 :
 sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
feature 들의 분산 값 :
 sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


#### 최대-최소 정규화
- MinMaxScaler: 데이터값을 0과 1 사이의 범위 값으로 변환

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('feature 들의 최소 값 :\n', iris_df_scaled.min())
print('feature 들의 최대 값 :\n', iris_df_scaled.max())

feature 들의 최소 값 :
 sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
feature 들의 최대 값 :
 sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


#### 스케일링 주의사항

In [ ]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array = np.arange(0,11).reshape(-1, 1)
test_array = np.arange(0,6).reshape(-1, 1)

scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터 : ', np.round(train_array.reshape(-1), 2))
print('Scaled train_array 데이터 : ', np.round(train_scaled.reshape(-1), 2))

#scaler.fit(test_array)
test_scaled = scaler.transform(test_array)

print('\n원본 test_array 데이터 : ', np.round(test_array.reshape(-1), 2))
print('Scaled test_array 데이터 : ', np.round(test_scaled.reshape(-1), 2))

원본 train_array 데이터 :  [ 0  1  2  3  4  5  6  7  8  9 10]
Scaled train_array 데이터 :  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array 데이터 :  [0 1 2 3 4 5]
Scaled test_array 데이터 :  [0.  0.1 0.2 0.3 0.4 0.5]
