<a href="https://colab.research.google.com/github/jangje0908/sesac/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Lecture.1 Why and How NumPy?

# Lecture.2 Objects and ndarrys

## Objects in Python

In [ ]:
# type() Functuon
a = []
b = {'a':1, 'b':2, 'c':3}
c = (1, 2, 3)

print(type(a))
print(type(b))
print(type(c))

<class 'list'>
<class 'dict'>
<class 'tuple'>


In [ ]:
# Object = Data + Method
a = [1, 2, 3]
a.append(4)
print(a)

[1, 2, 3, 4]


In [ ]:
# dir() Function
a = [1, 2, 3]
for attr in dir(a):
  print(attr)

__add__
__class__
__class_getitem__
__contains__
__delattr__
__delitem__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__getitem__
__gt__
__hash__
__iadd__
__imul__
__init__
__init_subclass__
__iter__
__le__
__len__
__lt__
__mul__
__ne__
__new__
__reduce__
__reduce_ex__
__repr__
__reversed__
__rmul__
__setattr__
__setitem__
__sizeof__
__str__
__subclasshook__
append
clear
copy
count
extend
index
insert
pop
remove
reverse
sort


In [ ]:
# dir() Function
a = {'a':1, 'b':2, 'c':3}
for attr in dir(a):
  print(attr)

__class__
__class_getitem__
__contains__
__delattr__
__delitem__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__getitem__
__gt__
__hash__
__init__
__init_subclass__
__ior__
__iter__
__le__
__len__
__lt__
__ne__
__new__
__or__
__reduce__
__reduce_ex__
__repr__
__reversed__
__ror__
__setattr__
__setitem__
__sizeof__
__str__
__subclasshook__
clear
copy
fromkeys
get
items
keys
pop
popitem
setdefault
update
values


In [ ]:
# Specual Method Examples
a, b = 4, 2

print(a - b, a.__sub__(b))
print(a * b, a.__mul__(b))
print(a ** b, a.__pow__(b))
print(a / b, a.__truediv__(b))
print(a // b, a.__floordiv__(b))
print(a % b, a.__mod__(b))

2 2
8 8
16 16
2.0 2.0
2 2
0 0


In [ ]:
# dir() Function - Methods of Different Objects
a = [1, 2, 3]
for attr in dir(a):
  print(attr)

a = {'a':1, 'b':2, 'c':3}
for attr in dir(a):
  print(attr)

__add__
__class__
__class_getitem__
__contains__
__delattr__
__delitem__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__getitem__
__gt__
__hash__
__iadd__
__imul__
__init__
__init_subclass__
__iter__
__le__
__len__
__lt__
__mul__
__ne__
__new__
__reduce__
__reduce_ex__
__repr__
__reversed__
__rmul__
__setattr__
__setitem__
__sizeof__
__str__
__subclasshook__
append
clear
copy
count
extend
index
insert
pop
remove
reverse
sort
__class__
__class_getitem__
__contains__
__delattr__
__delitem__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__getitem__
__gt__
__hash__
__init__
__init_subclass__
__ior__
__iter__
__le__
__len__
__lt__
__ne__
__new__
__or__
__reduce__
__reduce_ex__
__repr__
__reversed__
__ror__
__setattr__
__setitem__
__sizeof__
__str__
__subclasshook__
clear
copy
fromkeys
get
items
keys
pop
popitem
setdefault
update
values


## ndarray Object of NumPy

In [ ]:
# ndarray Objects
a = np.array([1, 2, 3])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
a = np.array([1, 2, 3])
for attr in dir(a):
  print(attr)

T
__abs__
__add__
__and__
__array__
__array_finalize__
__array_function__
__array_interface__
__array_prepare__
__array_priority__
__array_struct__
__array_ufunc__
__array_wrap__
__bool__
__class__
__class_getitem__
__complex__
__contains__
__copy__
__deepcopy__
__delattr__
__delitem__
__dir__
__divmod__
__dlpack__
__dlpack_device__
__doc__
__eq__
__float__
__floordiv__
__format__
__ge__
__getattribute__
__getitem__
__gt__
__hash__
__iadd__
__iand__
__ifloordiv__
__ilshift__
__imatmul__
__imod__
__imul__
__index__
__init__
__init_subclass__
__int__
__invert__
__ior__
__ipow__
__irshift__
__isub__
__iter__
__itruediv__
__ixor__
__le__
__len__
__lshift__
__lt__
__matmul__
__mod__
__mul__
__ne__
__neg__
__new__
__or__
__pos__
__pow__
__radd__
__rand__
__rdivmod__
__reduce__
__reduce_ex__
__repr__
__rfloordiv__
__rlshift__
__rmatmul__
__rmod__
__rmul__
__ror__
__rpow__
__rrshift__
__rshift__
__rsub__
__rtruediv__
__rxor__
__setattr__
__setitem__
__setstate__
__sizeof__
__str__
__sub__
__su

In [ ]:
# Element-wise Operations of ndarrays
u = [1, 2, 3]
v = [4, 5, 6]

w = u + v
print(w)

[1, 2, 3, 4, 5, 6]


In [ ]:
# Element-wise Operations of ndarrays
u = [1, 2, 3]
v = [4, 5, 6]

w = u + v
print(w)


w = [0] * len(u)
for data_idx in range(len(u)):
  w[data_idx] = u[data_idx] + v[data_idx]
print(w)

[1, 2, 3, 4, 5, 6]
[5, 7, 9]


In [ ]:
# Element-wise Operations of ndarrays
# with Python Lists
u = [1, 2, 3]
v = [4, 5, 6]

w = [0] * len(u)
for data_idx in range(len(u)):
  w[data_idx] = u[data_idx] + v[data_idx]
print(w)


# with ndarray
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

print(u + v)

[5, 7, 9]
[5 7 9]


In [ ]:
# Element-wise Operations of ndarrays
# with Python Lists
M = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
N = [[11, 12, 13], [14, 15, 16], [17, 18, 19]]

n_row, n_col = len(M), len(M[0])  # 3, 3

P = [[0]*n_col for _ in range(n_col)]  # [0]*3 for _ in range(3)
for row_idx in range(n_row):           # for row_idx in range(3) -> 0, 1, 2
  for col_idx in range(n_col):         # for col_idx in range(3) -> 0, 1, 2
    P[row_idx][col_idx] = M[row_idx][col_idx] + N[row_idx][col_idx]

for P_row in P:
  print(P_row)


# with ndarrays
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

N = np.array([[11, 12, 13],
              [14, 15, 16],
              [17, 18, 19]])
print(M + N)

[12, 14, 16]
[18, 20, 22]
[24, 26, 28]
[[12 14 16]
 [18 20 22]
 [24 26 28]]


# Lecture.3 Making ndarrays

## Shapes of ndarrays

In [ ]:
# Shapes of ndarrays
scalar_np = np.array(3.14)
vec_np = np.array([1, 2, 3])
mat_np = np.array([[1, 2], [3, 4]])
tensor_np = np.array([[[1, 2, 3],
                        [4, 5, 6]],
                       [[11, 12, 13],
                        [14, 15, 16]]])

print(scalar_np.shape)
print(vec_np.shape)
print(mat_np.shape)
print(tensor_np.shape)

print(len(()))
print(len((3,)))
print(len((2, 2)))
print(len((2, 2, 3)))

()
(3,)
(2, 2)
(2, 2, 3)
0
1
2
3
